### ISSUE TITLE
Syntax error with tetra_demod.py

### ISSUE THREAD

**Issue by dl1hrc** [Tim---/tetra-toolkit#1]
Hi Tim,
I get the following error messages with GR version 3.8.1.0 when I try to start tetra_rx.grc or tetra_demod.grc:

Traceback (most recent call last):
  File "/home/adi/tetra-sdr/lime-tetra/tetra-toolkit/grc/tetra_rx.py", line 40, in <module>
    from tetra_demod import tetra_demod  # grc-generated hier_block
  File "/home/adi/tetra-sdr/lime-tetra/tetra-toolkit/grc/tetra_demod.py", line 124
    self.mmse_resampler_xx_0 = filter.mmse_resampler_cc(, )
                                                        ^
SyntaxError: invalid syntax

>>> Done (return code 1)

Kind regards
Adi

**Comment by Tim---** [comment]
Hi,

Well, this project is kind of old, and I guess GNUradio is not really known for its backwards compatibility :).
If I remember correctly, I included the screenshots to anticipate breaking changes in the futures.

I guess you are probably better off creating the circuit from scratch. You can use the screenshots for the blocks and connections, and get the formula of computes values from the GRC files (it's just XML).

However, I think GNUradio introduced the "constellation" decoder and objects which looked really powerful.
I think this would be probably better, since it should only take two blocks to get a working receiver.
EDIT: oh. I just looked at the screenshot and I am using a constellation decoder. Well, you can forget about that last paragraph :).
